version: 2.1

orbs:
  android: circleci/android@2.1.2
  flutter: circleci/flutter@1.1.0

commands:
  install-flutter:
    steps:
      - flutter/install_sdk_and_pub:
          flutter_version: 3.3.9
      - flutter/install_android_gradle
      - flutter/install_android_gem
      - run: flutter pub run build_runner build --delete-conflicting-outputs
  dart-analyze:
    steps:
      - run:
          name: Check analyze
          command: |
            flutter analyze || exit

  build-android:
    description: Builds APK for Android
    steps:
      - run:
          command: flutter build apk
          name: Build APK
      - store_artifacts:
          path: ~/repo/build/app/outputs/flutter-apk/app-develop-debug.apk

  format:
    description: Run checks if Flutter code is formatted
    steps:
      - run:
          command: >-
            flutter format --set-exit-if-changed . || { echo 'Format check
            failed'; exit 1; }
          name: Analyze
  test:
    description: Runs the tests of your Flutter app
    steps:
      - run:
          command: flutter test
          name: Test

  # install-android-ruby-dependencies:
  #   steps:
  #     - restore_cache:
  #         key: 1-gems-{{ checksum "android/Gemfile.lock" }}
  #     - run:
  #         name: Bundle check
  #         command: cd ~/android && bundle check || bundle install --path vendor/bundle
  #     - save_cache:
  #         name: Save cache
  #         key: 1-gems-{{ checksum "android/Gemfile.lock" }}
  #         paths:
  #           - vendor/bundle

jobs:
  setup-and-format:
    executor:
      name: android/android-machine
      tag: 2021.10.1
    steps:
      - install-flutter
      - format
      - dart-analyze
      - test
  build-android-apk:
    executor: android/android-machine
      tag: 2021.10.1
    steps:
      - build-android
      - store_artifacts:
          path: ~/repo/build/app/outputs/flutter-apk/app-develop-debug.apk
          destination: android.apk

  app-distribution-android:
    executor:
      name: android/android-machine
      tag: 2021.10.1
    steps:
      - run: cd ~/repo/android && bundle exec fastlane upload_firebase

workflows:
  main:
    jobs:
      - setup-and-format
      - build-android-apk:
          requires:
            - setup-and-format
      - app-distribution-approval:
          type: approval
          requires:
            - setup-and-format
      - app-distribution-android:
          requires:
            - app-distribution-approval